[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
dotenv = "0.15" # Optional for managing environment variables
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-rustls-ring", "postgres" ] }
tokio = {version = "1", features = ["full"]}